apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupytercluster-data
  namespace: jupytercluster
  labels:
    app: jupytercluster
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

