{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jupytercluster.fullname" . }}
  labels:
    {{- include "jupytercluster.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jupytercluster.fullname" . }}
  labels:
    {{- include "jupytercluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jupytercluster.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "jupytercluster.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

